/*
 * Copyright (C) 2009 - 2018 Turbonomic, Inc.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
package com.turbonomic.protoc.plugin.common.generator;

import org.stringtemplate.v4.ST;

/**
 * This class contains templates required for code generation.
 */
class Templates {
    private Templates() {}

    static ST file() {
        return new ST(FILE_TEMPLATE);
    }

    private static final String FILE_TEMPLATE =
        "// Generated by the <pluginName> compiler plugin.  DO NOT EDIT!\n" +
        "// source: <protoSourceName>\n" +
        "package <pkgName>;" +

        "<imports>" +
        "@javax.annotation.Generated(" +
                "value = \"by <pluginName> compiler plugin\"," +
                "comments = \"Source: <protoSourceName>\")" +
        "public class <outerClassName> {" +
            "<messageCode>" +
            "<enumCode>" +
            "<serviceCode>" +
        "}";
}
